"""refrebce id column

Revision ID: 9932f7df7c0c
Revises: 3c3d1576f430
Create Date: 2024-10-18 11:02:27.741760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9932f7df7c0c'
down_revision = '3c3d1576f430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refrence_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_app_post_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refrence_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refrence_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cart', schema=None) as batch_op:
        batch_op.drop_column('refrence_id')

    with op.batch_alter_table('user_app_post_data', schema=None) as batch_op:
        batch_op.drop_column('refrence_id')

    with op.batch_alter_table('user_app', schema=None) as batch_op:
        batch_op.drop_column('refrence_id')

    # ### end Alembic commands ###
